URL=https://github.com/anyproto/anytype-ts/releases/download/v0.44.7-alpha/anytype-0.44.7-alpha.tar.gz

get_filename_from_url() {
    local url="$1"
    local filename=$(basename "$url")
    echo "$filename"
}

clean() {
    rm -rf anytype-0.44.7-alpha
    rm -rf $(get_filename_from_url $URL)
}

post_install() {
    wget $URL
    tar -xf $(get_filename_from_url $URL)
    mv -f anytype-0.44.7-alpha /opt/anytype
    clean
}



