post_install() {
  echo "Importing SunnyOS GPG key..."
  cat <<EOF | gpg --import
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZ3YY6RYJKwYBBAHaRw8BAQdAsSaAxQSGYjqusewyK9w16q1cZXR0l28cMvZJ
NUZVUx60F1NwaWR5IDxzcGlkeUBzcHBpZHkuaW4+iJkEExYKAEEWIQRgdVWARw34
mHAB7/xNkRByhomjZAUCZ3YY6QIbAwUJAeEzgAULCQgHAgIiAgYVCgkICwIEFgID
AQIeBwIXgAAKCRBNkRByhomjZIWvAQDfdiYrnFgUbY8UXVWMdAvw/s11iFQBYE+7
RUbwXV90VQEA2s+yO3e6ZsuLthuXPSfZzlctFVs4yv9iu3vqu+db2Q64OARndhjp
EgorBgEEAZdVAQUBAQdAJQeehMfalPC3CSSmDOAHzvn36oSUmdfrgu3MbsJTEmYD
AQgHiH4EGBYKACYWIQRgdVWARw34mHAB7/xNkRByhomjZAUCZ3YY6QIbDAUJAeEz
gAAKCRBNkRByhomjZGXzAP4xBLHWzmdQimkTR2ElFCiJdFb1k07nunr1W2RDNTaL
cgEAn6M/erIEDwS+qtZSqm8SKE6ALadSzuLSaoVr8A+9cQI=
=JJqD
-----END PGP PUBLIC KEY BLOCK-----
EOF
  gpg --edit-key 8689A364 trust quit
  echo "SunnyOS GPG key imported successfully."
}

post_upgrade() {
  post_install
}

pre_remove() {
  echo "Removing SunnyOS GPG key..."
  gpg --delete-key 8689A364
  echo "SunnyOS GPG key removed."
}
